### ISSUE TITLE
Anvil 2.5.0-beta09 gradle plugin does not add `build/anvil/main/generated` folder to main sourceSet.

### ISSUE THREAD

**Issue by IlyaGulya** [square/anvil#1007]
Hi!
I've upgraded Anvil to `2.5.0-beta09` and found out that I have to add `build/anvil/main/generated` folder to main sourceSet manually (see https://github.com/IlyaGulya/anvil-utils/blob/e26d3991e59be56f6695579aaff8a21094e68143/samples/build.gradle.kts#L19)

Otherwise build fails because code generated by custom code generators is not visible.
Here's sample project: https://github.com/IlyaGulya/anvil-utils/tree/e26d3991e59be56f6695579aaff8a21094e68143/samples

**Comment by RBusarow** [comment]
Thank you for the repro!  That was helpful.

Anvil does add the `build/anvil/____/generated` directory to the source set, [here](https://github.com/square/anvil/blob/70db0216c240b18052f56ceb9e5a6775327dc780/gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt#L183-L201).

In your sample, though, the unresolved `DefaultTestApi_AssistedFactory_Impl` doesn't come from Anvil at all.  It would come from Dagger's generator using Kapt.  The problem is that the Kapt generation doesn't happen until after Anvil is done, so you can't reference those Kapt-generated types in the generated Anvil code.

**Comment by IlyaGulya** [comment]
@RBusarow yeah, sorry, I've forgot to enable `generateDaggerFactories` 🙂 . Thanks!
