### ISSUE TITLE
Support extension functions in modules

### ISSUE THREAD

**Issue by japplin** [square/anvil#147]
``` kotlin
@Module
class MyModule {
    @Provides fun AppCompatActivity.activity(): Activity = this
}
```
Gives me this error `MyModule_ActivityFactory.kt: (20, 82): Unresolved reference: activity`

**Comment by vRallev** [comment]
This won't be fixed. The generated code wouldn't compile in Kotlin. The generated code would need to call `myModule.activity()`, but it also requires the receiver type.

I suggest you use a normal function.

**Comment by bubenheimer** [comment]
Could this issue be reopened? It complicates migrations from Dagger.

The problem can be addressed readily via the following in codegen, perhaps this was not an option yet in Kotlin at the time that this issue was created. I've been using this pattern for quite a while, since at least Kotlin 1.5.x, but likely earlier:

    with(myModule) { appCompatActivity.activity() }

**Comment by vRallev** [comment]
I'm not eager to that. I'm open to contributions, but we won't implement this anytime soon.
