### ISSUE TITLE
Build version of Anvil for non-embedded Kotlin compiler.

### ISSUE THREAD

**Issue by jongerrish** [square/anvil#155]
For those building with the regular non-embeddable compiler (e.g: Bazel) wishing to use Anvil it requires a separate version of Anvil to be built because the compiler plugin API is shaded for the embedded compiler.

I think this is a fundamental bug with the Kotlin compiler API and should be fixed but in the meantime it seems other plugin developers ship two versions

See: https://youtrack.jetbrains.com/issue/KT-43086

**Comment by vRallev** [comment]
That's a very unfortunate issue. However, maintaining two versions for us isn't really an option, because it involves changes for dependencies and in code. I can only suggest to fork the repo and maintain the duplicate version yourself.

Internally, our Bazel team ran into the same issue. They used Jarjar for Anvil as part of the Bazel Kotlin compiler plugin. Maybe that's an option for you?

**Comment by jongerrish** [comment]
Hey Ralf,

If you follow the jet brains link you can see another plugin developer who basically copied how Jetbrains build two versions of their plugins. Doesn't need code changes, I believe you just build against the regular APIs then run the shading on it to produce the embeddable.

I've been talking with Christian and I think the consensus we reached was Bazel should probably use the embeddable compiler to be more gradle-like.

**Comment by restingbull** [comment]
I'll merge the support for embedded compiler plugins to rules_kotlin this weekend. Considering that compiler plugins can, and will (multiple tutorials out there fail to distinguish between them) rules_kotlin will need to support both.

**Comment by vRallev** [comment]
Seems like the fix will be implemented in the Kotlin rules for Bazel.
