### ISSUE TITLE
Support delaying generating subcomponents

### ISSUE THREAD

**Issue by vRallev** [square/anvil#160]
Imagine this module dependency tree:
```
:app -> :lib-a
    \-> :lib-b
```
`:lib-a` creates a subcomponent with `@MergeSubcomponent`. Note that Dagger won't generate any code in `:lib-a`. `:app` creates the component with `@MergeComponent`. That's where Dagger generates the code for the subcomponent. 

If `:lib-b` contributes to the scope of the subcomponent in `:lib-a`, then the contribution won't be picked up without adding the dependency `:lib-a -> :lib-b`. This can lead to confusing situations. 

Anvil should generate the code for the subcomponent in the `:app` module and then pick up all contributed bindings. This would also solve the problem that Dagger components need to be declared twice in the main source set and the source set for tests, if the test components merge different classes.

**Comment by vRallev** [comment]
I think I have an API that I'd be happy with. In our Square codebase we usually have this pattern:
```kotlin
@Subcomponent
interface LoggedInComponent

@ContributesTo(AppScope::class)
interface ParentLoggedInComponent {
  fun loggedInComponent(): LoggedInComponent
}
```
I propose to introduce a new annotation `@ContributesSubcomponent`:
```kotlin
@ContributesSubcomponent(
  scope = LoggedInScope::class,
  parentScope = AppScope::class
)
interface LoggedInComponent
```
The API for `@ContributesComponent` is similar to `@MergeSubcomponent`, but the behavior is different. Anvil would generate the actual subcomponent whenever the component of the parent scope is merged. The trigger would be:
```kotlin
@MergeComponent(AppScope::class)
interface AppComponent
```
Then in this Gradle module Anvil would generate the following:
```kotlin
@MergeSubcomponent(
  scope = LoggedInScope::class
)
public interface AnvilLoggedInComponent : LoggedInComponent

@ContributesTo(scope = ParentScope::class)
public interface AnvilParentLoggedInComponent : ParentLoggedInComponent {
  public override fun component(): AnvilLoggedInComponent
}
```
Note that the generated code itself uses Anvil annotations and the functionality would work as expected. If Anvil can't find a contributed interface like `ParentLoggedInComponent`, then it would still generate `AnvilParentLoggedInComponent`, but not add the super type. Some code uses reflection to call the generated method.

This approach should work for the simple cases. I did a quick spike for `@Subcomponent.Factory` and it's possible to support that. I did the same for `@Subcomponent.Builder`, but ran into Dagger compile errors that I need to eventually report. I also need to note that subcomponent added in Dagger modules with `@Module(subcomponents = [Abc::class])` can't be supported, because Anvil won't rewrite the annotation.

**Comment by chrisjenx** [comment]
Some minor thoughts/ideas/suggestions;

We generally use `@Subcomponent.Builder` almost exclusively, although thinking about it, maybe moving to `dagger.Subcomponent.Factory` would probably safer in the long run - and would happily take that limitation for the respective gains here!

I put together how I understand a full example to look like based on what you defined.

```
@ContributesSubcomponent(
  scope = FeatureScope::class, parentScope = AppScope::class,
  modules = [], excludes = []
)
interface FeatureComponent {
  fun inject(activity: FeatureActivity)
  @Subcomponent.Factory
  interface Factory {
    fun build(@BindsInstance instance: SomeType): FeatureComponent
  }
  @ContributesTo(AppScope::class)
  interface Parent {
    fun featureComponent(): FeatureComponent.Factory
  }
}
```

One thing that sticks out here, is that we always define our `Parent`, as when we wire our Activities, we have a overridden method like:
```
override fun inject(parent: Parent) {
  parent.featureComponent().build(intent.getParcelable()).inject(this)
}
```

Depending how flexible you want Anvil to be there could be multiple solutions, but I don't think defining `parentScope = AppScope::class` and `@ContributesTo(AppScope::class) interface Parent` probably makes sense? I can see people getting confused with that too. 

- One idea is that, `parentScope=` is only required if no `@ContributesTo() interface Parent` is defined?
- Or maybe instead, it's a `parent=FeatureComponent.Parent::class` instead?
- Or there is no `parent` value at all inside the `@ContributesSub`, then all inner interfaces with `@ContributesTo()` are seen as "parents"?


From the implementation POV:

The way I understand this working, is that Anvil only generates the `@MergeSubcomponent` when the `@MergeComponent(scope = ParentScope::class)` is present? 

So in our case, we define `@Subcomponents` in feature modules, the `@MergeComponent(scope = ParentScope::class)` only exists in the App module, so in most cases Anvil will defer generation of the `AnvilSubcomponent` to dagger in the App module right?

But in the case of test source set, we have a `TestAppComponent` defined with  `AppScope::class`, when Anvil evaluates the test source set, it would see that it has that parent component to "ContributeTo" and generate that `AnvilSubcomponent` for the test source set so that dagger can generate then generate the graph correctly?

All in all this sounds awesome!

**Comment by vRallev** [comment]
A PR for this feature is up.
