### ISSUE TITLE
Anvil 2x slower than Dagger

### ISSUE THREAD

**Issue by aitorvs** [square/anvil#172]
I recently added Anvil to a project, that had both Dagger and dagger-android (sigh), and I noticed 2x-3x clean/incremental build times .

I managed to repro it in a [sample project](https://github.com/aitorvs/android-scaffolding/pulls). First commit of that PR uses Anvil, second commit uses Dagger to contribute a module to the `AppComponent`.
Running `gradlew --scan buildDegug` for clean and incremental builds, in both commits yields the following:

with Anvil (1st commit)

* clean build -> https://gradle.com/s/bh7cxidxzkkc4
* incremental build -> https://gradle.com/s/mmcg6ee3wed4y

with Dagger (second commit)

* clean build -> https://scans.gradle.com/s/5tz6skgnhtxxa
* incremental build -> https://gradle.com/s/a75gqnc3uamcu

For the incremental builds, it seems that `app:compileDebugKotlin` is not incremental when using Anvil, I was not able to figure out why.

Note: To trigger incremental builds I just added a timber line into the `Dummy#dummy` method

**Comment by vRallev** [comment]
This is unfortunate, but expected to some degree. I don't have access to your project, but from the build scans I can tell that you have three modules. You use Kapt in all of them and the stub generating task is [no longer incremental](https://github.com/square/anvil#limitations). However, `app:compileDebugKotlin` should still be incremental for incremental builds. Incremental compilation for this task is only disabled, if the compiler plugin classpath changes, e.g. when adding or upgrading Anvil. This workaround is needed for https://youtrack.jetbrains.com/issue/KT-38570. 

If you apply Kapt to all modules and all stub generating tasks are no longer incremental [due to Anvil](https://github.com/square/anvil/blob/main/gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt#L194-L204), then this could have a significant impact on build times. I heard from another project with a large application module, that the negative impact for them was too big as well. In our project the application modules are tiny. They are the only modules applying Kapt and everywhere else [we use Anvil](https://github.com/square/anvil#dagger-factory-generation). We don't use any other annotation processors besides Dagger itself. 

Mixing Java and Kotlin could also have a negative impact (annotation processor usually generate Java files).

**Comment by naixx** [comment]
I think the issue is that compile task is being slower than it should be. This and stubs not being incremental makes build much slower

**Comment by aitorvs** [comment]
Thanks for the answers, I appreciate them a lot. 
I think the main contributor is the `app:compileDebugKotlin` task, that 2x-3x when adding anvil. I thought the reason is bc is no longer incremental for incremental builds. Besides classpath changes, what else can make it not incremental when adding anvil?


Sorry @vRallev, I didn't realised the sample repo was kept private 🤦‍♂️. Right now I am afk but as soon as I'm back I will give access.

**Comment by vRallev** [comment]
There's definitely some slight overhead when applying Anvil for the `compileKotlin` task. When we measured the overhead for our project, it added [around 4%](https://github.com/square/anvil#performance) to the total build time, but nowhere near to 2x. 

You can find the code for that [here](https://github.com/square/anvil/blob/main/gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt#L220). Notice that you can add `--info` when building with Gradle and then you should see the Anvil [log statements](https://github.com/square/anvil/blob/main/gradle-plugin/src/main/java/com/squareup/anvil/plugin/AnvilPlugin.kt#L259-L261) whether the compile task is incremental or not.

**Comment by aitorvs** [comment]
@vRallev thanks a lot. I have fixed the access to the [sample project now](https://github.com/aitorvs/android-scaffolding/pull/1).

I have run with `:app:assembleDebug --info` and it seems the task `:app:compileDebugKotlin` is incremental

```
Task ':app:compileDebugKotlin' is not up-to-date because:
  Input property 'classpath' file /Users/aitor/code/android-scaffolding/dummy/build/intermediates/compile_library_classes_jar/debug/classes.jar has changed.
Anvil: Incremental compilation enabled: true (compile)
Anvil: Use precise java tracking: false
```

However, when using anvil it takes a lot more time.

With dagger
```
Task ':app:compileDebugKotlin' is not up-to-date because:
  Input property 'classpath' file /Users/aitor/code/android-scaffolding/dummy/build/intermediates/compile_library_classes_jar/debug/classes.jar has changed.
Anvil: Incremental compilation enabled: true (compile)
Anvil: Use precise java tracking: false
...
...
:app:compileDebugKotlin (Thread[Execution worker for ':',5,main]) completed. Took 0.055 secs.
```

with anvil
```
Task ':app:compileDebugKotlin' is not up-to-date because:
  Input property 'classpath' file /Users/aitor/code/android-scaffolding/dummy/build/intermediates/compile_library_classes_jar/debug/classes.jar has changed.
Anvil: Incremental compilation enabled: true (compile)
Anvil: Use precise java tracking: false
...
...
:app:compileDebugKotlin (Thread[Execution worker for ':' Thread 11,5,main]) completed. Took 0.787 secs.
```
Could you shed some light as to why this happens?

**Comment by vRallev** [comment]
I assume some overhead comes from the fact of applying the compiler plugin in general. There's for sure some overhead in the compiler itself, but I can't say how much. Your modules of the sample project are tiny. If Anvil needs to process most of the classes, then the overhead compared to total build time is larger. With more code that Anvil ignores the partial overhead would be smaller. We didn't see such a significant difference, but I'm sure this statement is unsatisfying for you.

**Comment by vRallev** [comment]
I don't have any other recommendations. Like I said we only enable the Dagger annotation processor and Kapt in the final app module. Everywhere else we rely on Anvil to [generate Dagger factories](https://github.com/square/anvil#dagger-factory-generation). We don't use any other annotation processors. Because of that we saw a significant improvement in performance.

**Comment by naixx** [comment]
Unfortunately, the issue exists. Looks like compile task is no longer incremental. Instead of the usual 15-20s, it takes about 70-80 with only 1 or 2 files changed (according to build analyzer). 
generateStubs is not incremental as expected

**Comment by vRallev** [comment]
I don't see why the compile task shouldn't be incremental. How did you confirm it's not incremental?
