### ISSUE TITLE
Anvil does not implement all contributing components?

### ISSUE THREAD

**Issue by L-Andrade** [square/anvil#206]
Hello,

I was migrating a side-project from standard Dagger2 to Anvil. It was going pretty well, it's a bit easier to do some things and it's compiling. I've followed quite a bit of what is done in the sample app, although the sample and my app are a bit different (in terms of modules).

Here's the PR with the 'migration': https://github.com/L-Andrade/Xous/pull/4

My problem is that when I'm getting the component from `ComponentHolder`, for example in `HomeFragment` with `ComponentHolder.component<HomeComponent>().inject(this)` it can not find the component interface of that module, throwing an exception since the list 'is empty' - which is true since supposedly the core component is not implementing `HomeComponent`.

Am I missing something here? The module with the main component (`CoreComponent`, which uses `MergeComponent`) has the compiler kapt dependency, while all other modules use `anvil { generateDaggerFactories = true }`, and have a component with `ContributesTo`.

I'm sorry if this doesn't belong here.

Thank you in advance.

**Comment by vRallev** [comment]
I'm sorry, but I don't have the time to take a look at this PR. It sounds more like there's an issue with the setup rather than an issue with Anvil itself. I don't have the bandwidth to dig into your project.

**Comment by L-Andrade** [comment]
Alright, thanks anyway. I'll close the issue.

**Comment by RBusarow** [comment]
> supposedly the core component is not implementing `HomeComponent`. 

`CoreComponent` _can't_ implement `HomeComponent`.  Your `:home` module is not a dependency of `:core`.  

`@ContributesTo` is sensitive to your dependency graph.  This is explained a little bit in the [quick start](https://github.com/square/anvil#quick-start) section of the README.
> `@ContributesTo` can be added to Dagger modules and component interfaces that should be included in the Dagger component. Classes with this annotation are automatically merged by the compiler plugin as long as they are on the compile classpath.

So if you want to have a mono-component, it needs to go in a module which has access to everything (typically the application module).  By doing this, the dependency graph is basically handled automatically.  

This also minimizes the use of `kapt` if using the Anvil factory generation, because the only module using Dagger's compiler is the app module.  Everything else can be handled by Anvil.

The basic structure winds up looking like this:

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/9890900/108578597-b768a600-72e8-11eb-9037-c4d62ff5ba6f.png">

**Comment by L-Andrade** [comment]
@RBusarow Ah, that makes sense then, my bad for missing that.

That detail of having `api` to `:core` is also important.

Thanks for taking your time to dig into it!

**Comment by RBusarow** [comment]
@L-Andrade Glad it helps. 👍
