### ISSUE TITLE
Custom code generator will not run without generateDaggerFactories = true

### ISSUE THREAD

**Issue by bubenheimer** [square/anvil#589]
It seems that custom code generation via `anvil(project('my_code_generator'))` will not run without `generateDaggerFactories = true`. I am seeing this with 2.4.0. Did not see it mentioned in the documentation.

In my case I have a module where I need to run both the dagger processor and my custom Anvil code generator, which does not seem possible at the moment. It's tricky to split up the module because it pulls in a lot of other stuff for the Dagger component, and I'd have to create a separate module that also pulls in everything else just for a tiny bit of custom codegen.

**Comment by RBusarow** [comment]
Anvil uses `CodeGenerator.isApplicable(...)` to determine whether it should invoke your custom generator.  If your implementation is hard-coded to return `true`, it will always run.  This is unchanged in 2.4.0.

If your generated code is directly referencing other generated code, that other generated code must come from Anvil and not kapt/Dagger.  This is because kapt executes after Anvil.

**Comment by bubenheimer** [comment]
Thank you! I missed that `isApplicable()` wasn't returning `true` in the code template that I started out from in this case.
