### ISSUE TITLE
Access generic type from the Anvil compiler plugin

### ISSUE THREAD

**Issue by jakoss** [square/anvil#635]
I have this code:

``` kotlin
class NewClass : BaseClass<NewClassRelatedType>()
```

What i want to achieve is to find all classes that are inheriting the `BaseClass` (easy to do), but after that i want to get the type of the `NewClassRelatedType` that was passed as a generic type.

I know about type erasure issue, but since Anvil is kotlin compiler plugin the generic type should still be there? Am i mistaken? And if not - how can i achieve that without involving annotations?

I tried to do that:
```kotlin
val superClass = reference.allSuperTypeClassReferences()
    .find {
        it.fqName == baseClassFqName
    } ?: return false
val type = superClass.typeParameters.firstOrNull() ?: return false
```
But it's saying that the type is `T`, which is not that helpful

**Comment by vRallev** [comment]
The type is `T`, because you ask for the generic type of class `BaseClass<T>`. Anvil has options to resolve the generic type `T` for the `NewClass` type. Please take a look at this unit test: https://github.com/square/anvil/blob/main/compiler/src/test/java/com/squareup/anvil/compiler/internal/reference/TypeReferenceTest.kt#L155

Does this help you?

**Comment by jakoss** [comment]
Works like a charm, thanks!
