### ISSUE TITLE
Generated Dagger factory should respect class internal visibility

### ISSUE THREAD

**Issue by Tapchicoma** [square/anvil#73]
Let's say we have a following a Gradle module with following Dagger module:
```kotlin
@Module
abstract class SomeModule {

    @Binds
    internal abstract fun bindSomeManager(impl: DelegatingSomeManager): SomeManager
}
```
where `DelegatingSomeManager` has `internal` visiblity  plus `@Inject` annotation on constructor. `SomeManager` interface has public visibility.

Generated `DelegatingSomeManager_Factory.kt` looks follwoing:
```kotlin
@Generated(
  value = ["com.squareup.anvil.compiler.AnvilComponentRegistrar"],
  comments = "https://github.com/square/anvil"
)
class DelegatingSomeManager_Factory() : Factory<DelegatingSomeManager> {
  override fun get(): DelegatingSomeManager = newInstance()

  companion object {
    @JvmStatic
    fun create(): DelegatingSomeManager_Factory = DelegatingSomeManager_Factory()

    @JvmStatic
    fun newInstance(): DelegatingSomeManager = DelegatingSomeManager()
  }
}
```

Kotlin compile task fails with following message:
```
'public' function exposes its 'internal' return type DelegatingSomeManager
```

Module compilation via Dagger kapt completes without error.

Most probably solution would be to generate factories with the same visibility modifier that class has.

**Comment by Tapchicoma** [comment]
Dagger is also generates Factory with public visibility and it works as kotlin internal visibility maps to Java public. Probably we just abusing interop, feel free to close this issue if no feasible solution is possible.

**Comment by Dkhusainov** [comment]
Facing exact same problem, as most of our modules encapsulate logic behind `interface`s with `internal` implementation.

**Comment by vRallev** [comment]
We have the policy internally to make all Dagger code public for this exact reason. Dagger assumes public, `internal` is treated as public in bytecode. The reason it doesn't fail with Dagger is because the internal code is referenced in generated Java code. Try to call an internal function from Java in a different module. You'll see an error. `internal` is misleading, because it implies that nothing outside of this module uses this code. That's wrong, Dagger uses and calls this code outside of the module.

There's also this issue which is important for `implementation` and `api` dependencies: https://github.com/google/dagger/issues/970 

The solution as is works as expected.

**Comment by neworld** [comment]
I suppose here is a discussion about this problem in dagger: https://github.com/google/dagger/issues/2589
